apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment-example
  template:
    metadata:
      labels:
        app: nginx-deployment-example
    spec:
      containers:
        - name: nginx
          image: gcr.io/modular-source-228811/uncut-nginx1:$SEMAPHORE_WORKFLOW_ID

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-example-svc
spec:
  type: NodePort
  selector:
    app: nginx-deployment-example
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  backend:
    serviceName: nginx-deployment-example-svc
    servicePort: 80
